-- require("items.apple")
-- require("items.menus")
require("items.clock")
require("items.calendar")
require("items.spaces")
-- require("items.front_app")
-- require("items.widgets")
-- require("items.media")
-- require("items.keylayout")
