[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
# padding.y = 10

decorations = "None"

blur = false

option_as_alt = "Both"

[font]
normal.family = "SauceCodePro Nerd Font"
normal.style = "Regular"

size = 14

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#003955"
foreground = "#b4f9f8"
dim_foreground = "#17E3FF"
bright_foreground = "#30FFF2"


[colors.normal]
black = "#002a3e"
red = "#FF7575"
green = "#5DFFAE"
yellow = "#F6FFAE"
blue = "#39CDFF"
magenta = "#ffcbe6"
cyan = "#30FFF2"
white = "#b4f9f8"

[colors.bright]
black = "#002a3e"
red = "#FFCBBA"
green = "#30ffc8"
yellow = "#FEFFD5"
blue = "#6ee7ff"
magenta = "#FFEBFE"
cyan = "#30FFF2"
white = "#b4f9f8"
