# macOS-specific Alacritty overrides

[window]
startup_mode = "SimpleFullscreen"
decorations = "Buttonless"
option_as_alt = "Both"

[[hints.enabled]]
command = "open"
hyperlinks = true
regex = "(https?|ftp)://[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
mouse.enabled = true
mouse.mods = "Command"
